const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const audio=$('#audio'), view=$('#view'), mini=$('#mini'), sheet=$('#sheet'), sheetBody=$('#sheetBody');
let db,tab='home',tracks=[],playlists=[],current=null,currentAudioURL=null,lastPositionSave=0,lrcCache={source:null,lines:[]},settings={shuffle:false,repeat:'off',volume:1,rate:1,remember:true,lyrics:true,accent:'#1ed760',sort:'newest'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid=()=>crypto.randomUUID(); const fmt=s=>!isFinite(s)?'0:00':`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open('MeloDB',3);r.onupgradeneeded=()=>{let d=r.result;['tracks','trackmeta','playlists','settings'].forEach(x=>{if(!d.objectStoreNames.contains(x))d.createObjectStore(x,{keyPath:'id'})})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{let r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{let r=db.transaction(store,'readwrite').objectStore(store).put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{let r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function metaOf(t){let {blob,...m}=t;return m} function saveMeta(t){return put('trackmeta',metaOf(t))} function getLRCLines(){let src=current?.syncedLyrics||'';if(lrcCache.source!==src){lrcCache={source:src,lines:parseLRC(src)}}return lrcCache.lines}
async function init(){await openDB();tracks=await all('tracks');let metas=await all('trackmeta');let mm=new Map(metas.map(m=>[m.id,m]));tracks=tracks.map(t=>({...t,...(mm.get(t.id)||{})}));playlists=await all('playlists');let s=(await all('settings'))[0];if(s)settings={...settings,...s};applySettings();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');}
function applySettings(){audio.volume=settings.volume;audio.playbackRate=settings.rate;document.documentElement.style.setProperty('--accent',settings.accent)}
function art(t,cls=''){return t.art?`<img class="art ${cls}" src="${t.art}" alt="">`:`<div class="art ${cls}">♫</div>`}
function parseLRC(text){let out=[];for(const raw of String(text||'').split(/\r?\n/)){let times=[...raw.matchAll(/\[(\d{1,3}):(\d{2})(?:[.:](\d{1,3}))?\]/g)];if(!times.length)continue;let lyric=raw.replace(/\[[^\]]+\]/g,'').trim();for(const m of times){let frac=m[3]||'0',ms=frac.length===3?+frac:frac.length===2?+frac*10:+frac*100;out.push({time:(+m[1])*60+(+m[2])+ms/1000,text:lyric||'♪'})}}return out.sort((a,b)=>a.time-b.time)}
function activeLRCIndex(lines,time){let i=-1;for(let n=0;n<lines.length;n++){if(lines[n].time<=time+.08)i=n;else break}return i}
function syncedLyricsHTML(t){let lines=(current&&t.id===current.id)?getLRCLines():parseLRC(t.syncedLyrics||'');if(!lines.length)return `<div class="lyrics-text">${t.lyrics?esc(t.lyrics):'<span class="sub">No saved lyrics yet.</span>'}</div>`;return `<div id="syncedLyrics" class="synced-lyrics">${lines.map((x,i)=>`<div class="lyric-line" data-li="${i}" data-time="${x.time}">${esc(x.text)}</div>`).join('')}</div>`}
function updateSyncedLyrics(){if(!current)return;let lines=getLRCLines(),box=$('#syncedLyrics');if(!box||!lines.length)return;let idx=activeLRCIndex(lines,audio.currentTime);if(idx<0||box.dataset.active==String(idx))return;let prev=box.querySelector('.lyric-line.active');if(prev)prev.classList.remove('active');let el=box.querySelector(`[data-li="${idx}"]`);if(el){el.classList.add('active');box.dataset.active=String(idx);el.scrollIntoView({behavior:'auto',block:'center'})}}
function row(t){return `<div class="row" data-play="${t.id}">${art(t)}<div class="meta"><div class="title">${esc(t.title)}</div><div class="sub">${esc(t.artist)}${t.album?' • '+esc(t.album):''}</div></div><button class="more" data-more="${t.id}">•••</button></div>`}
function render(){let h=new Date().getHours();$('#greeting').textContent=h<12?'Good morning':h<18?'Good afternoon':'Good evening';$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='home')home();if(tab==='search')search();if(tab==='library')library();if(tab==='settings')settingsView();renderMini();bindCommon()}
function home(){let recent=[...tracks].sort((a,b)=>b.added-a.added).slice(0,6);view.innerHTML=`<div class="hero">Your music, your way.</div>${tracks.some(t=>t.favorite)?`<button class="primary" id="liked">♥ Liked Songs</button>`:''}<h2>Recently added</h2>${recent.map(row).join('')||empty()}<h2>Your music</h2><div class="cards">${tracks.map(t=>`<div class="album" data-play="${t.id}">${art(t)}<div class="title">${esc(t.title)}</div><div class="sub">${esc(t.artist)}</div></div>`).join('')}</div>`;$('#liked')?.addEventListener('click',()=>showList('Liked Songs',tracks.filter(t=>t.favorite)))}
function search(){view.innerHTML=`<h2>Search</h2><input class="search" id="q" placeholder="Songs, artists or albums"><div id="results">${tracks.map(row).join('')||empty()}</div>`;$('#q').oninput=e=>{let q=e.target.value.toLowerCase();$('#results').innerHTML=tracks.filter(t=>(t.title+t.artist+t.album).toLowerCase().includes(q)).map(row).join('')||empty();bindCommon()}}
function library(){let sorted=[...tracks].sort((a,b)=>settings.sort==='title'?a.title.localeCompare(b.title):settings.sort==='artist'?a.artist.localeCompare(b.artist):settings.sort==='played'?(b.plays||0)-(a.plays||0):b.added-a.added);view.innerHTML=`<h2>Your Library</h2><div class="toolbar"><button class="primary" id="import">＋ Import Music</button><button class="pill" id="newPl">＋ Playlist</button><select class="pill" id="sort"><option value="newest">Recently added</option><option value="title">Title</option><option value="artist">Artist</option><option value="played">Most played</option></select></div>${playlists.length?`<h2>Playlists</h2>${playlists.map(p=>`<div class="playlist" data-pl="${p.id}"><b>${esc(p.name)}</b><div class="sub">${p.ids.length} songs</div></div>`).join('')}`:''}<h2>Songs</h2>${sorted.map(row).join('')||empty()}`;$('#sort').value=settings.sort;$('#sort').onchange=e=>{settings.sort=e.target.value;saveSettings();render()};$('#import').onclick=()=>$('#fileInput').click();$('#newPl').onclick=newPlaylist;$$('[data-pl]').forEach(x=>x.onclick=()=>{let p=playlists.find(p=>p.id===x.dataset.pl);showList(p.name,p.ids.map(id=>tracks.find(t=>t.id===id)).filter(Boolean),p)});}
function settingsView(){view.innerHTML=`<h2>Settings</h2><div class="setting"><span>Volume</span><input id="vol" type="range" min="0" max="1" step=".01" value="${settings.volume}"></div><div class="setting"><span>Playback speed</span><select id="rate" class="pill">${[.75,1,1.25,1.5,2].map(x=>`<option value="${x}" ${x==settings.rate?'selected':''}>${x}×</option>`).join('')}</select></div><div class="setting"><span>Shuffle</span><input id="shuffle" type="checkbox" ${settings.shuffle?'checked':''}></div><div class="setting"><span>Repeat</span><select id="repeat" class="pill"><option>off</option><option>all</option><option>one</option></select></div><div class="setting"><span>Remember position</span><input id="remember" type="checkbox" ${settings.remember?'checked':''}></div><div class="setting"><span>Show lyrics card</span><input id="showLyrics" type="checkbox" ${settings.lyrics?'checked':''}></div><div class="setting"><span>Accent</span><input id="accent" type="color" value="${settings.accent}"></div><h2>Sleep Timer</h2><div class="toolbar">${[15,30,45,60].map(m=>`<button class="pill timer" data-min="${m}">${m} min</button>`).join('')}<button class="pill" id="cancelTimer">Off</button></div><h2>Data</h2><button class="danger" id="reset">Reset settings</button>`;$('#repeat').value=settings.repeat;['shuffle','remember'].forEach(k=>$('#'+k).onchange=e=>{settings[k]=e.target.checked;saveSettings()});$('#showLyrics').onchange=e=>{settings.lyrics=e.target.checked;saveSettings()};$('#vol').oninput=e=>{settings.volume=+e.target.value;audio.volume=settings.volume;saveSettings()};$('#rate').onchange=e=>{settings.rate=+e.target.value;audio.playbackRate=settings.rate;saveSettings()};$('#repeat').onchange=e=>{settings.repeat=e.target.value;saveSettings()};$('#accent').oninput=e=>{settings.accent=e.target.value;applySettings();saveSettings()};$$('.timer').forEach(b=>b.onclick=()=>setSleep(+b.dataset.min));$('#cancelTimer').onclick=()=>setSleep(0);$('#reset').onclick=()=>{settings={shuffle:false,repeat:'off',volume:1,rate:1,remember:true,lyrics:true,accent:'#1ed760',sort:'newest'};applySettings();saveSettings();render()}}
function empty(){return `<div class="empty">No music yet.<br>Import audio from your iPhone Files app.</div>`}
function bindCommon(){$$('[data-play]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-more]'))return;play(x.dataset.play)});$$('[data-more]').forEach(x=>x.onclick=e=>{e.stopPropagation();trackMenu(x.dataset.more)})}
async function play(id){
  let t=tracks.find(x=>x.id===id);if(!t||!t.blob)return;
  try{
    audio.pause(); current=t; lrcCache={source:null,lines:[]};
    if(currentAudioURL)URL.revokeObjectURL(currentAudioURL);
    currentAudioURL=URL.createObjectURL(t.blob);
    audio.removeAttribute('src'); audio.src=currentAudioURL; audio.muted=false;
    audio.volume=Math.max(0,Math.min(1,Number(settings.volume??1))); audio.playbackRate=settings.rate||1; audio.load();
    await new Promise(resolve=>{if(audio.readyState>=1)return resolve();let done=()=>{audio.removeEventListener('loadedmetadata',done);resolve()};audio.addEventListener('loadedmetadata',done,{once:true});setTimeout(resolve,1500)});
    if(settings.remember&&t.position&&isFinite(audio.duration))audio.currentTime=Math.min(t.position,Math.max(0,audio.duration-.25));
    await audio.play(); t.plays=(t.plays||0)+1; saveMeta(t); renderMini(); nowPlaying(); mediaSession();
  }catch(err){console.error(err);alert('Melo could not start this audio file. Tap the song again, check the iPhone volume, and make sure Silent Mode is not the issue.');renderMini()}
}
function renderMini(){if(!current){mini.classList.add('hidden');return}mini.classList.remove('hidden');mini.innerHTML=`${art(current)}<div class="meta"><div class="title">${esc(current.title)}</div><div class="sub">${esc(current.artist)}</div></div><button class="icon" id="miniPlay">${audio.paused?'▶':'Ⅱ'}</button>`;mini.onclick=e=>{if(e.target.id==='miniPlay'){toggle();e.stopPropagation()}else nowPlaying()}}
function toggle(){if(!current)return;audio.paused?audio.play():audio.pause();renderMini();if(!sheet.classList.contains('hidden'))nowPlaying()}
function next(){if(!tracks.length)return;let i=tracks.findIndex(t=>t.id===current?.id);let t=settings.shuffle?tracks[Math.floor(Math.random()*tracks.length)]:tracks[(i+1+tracks.length)%tracks.length];play(t.id)}function prev(){if(audio.currentTime>4){audio.currentTime=0;return}let i=tracks.findIndex(t=>t.id===current?.id);play(tracks[(i-1+tracks.length)%tracks.length].id)}
function nowPlaying(){if(!current)return;sheet.classList.remove('hidden');sheetBody.innerHTML=`<div class="now glass-now"><div class="art-stage"><div class="art-glow" style="${current.art?`background-image:url('${current.art}')`:''}"></div>${art(current,'big')}</div><div class="meta"><div class="title" style="font-size:24px">${esc(current.title)}</div><div class="sub" style="font-size:16px">${esc(current.artist)}</div></div><input id="seek" class="range" type="range" min="0" max="${audio.duration||1}" value="${audio.currentTime||0}"><div class="times"><span id="ct">${fmt(audio.currentTime)}</span><span id="dur">${fmt(audio.duration)}</span></div><div class="controls"><button id="shuf" style="color:${settings.shuffle?'var(--accent)':'white'}">⤨</button><button id="prev">◀︎</button><button class="play" id="bigPlay">${audio.paused?'▶':'Ⅱ'}</button><button id="next">▶︎</button><button id="rep" style="color:${settings.repeat!=='off'?'var(--accent)':'white'}">↻</button></div><div class="toolbar center-tools"><button class="pill" id="fav">${current.favorite?'♥ Liked':'♡ Like'}</button><button class="pill" id="edit">✎ Edit</button><button class="pill" id="lyricsBtn">Lyrics / LRC</button><button class="pill" id="infoBtn">⌕ Music Info</button></div>${settings.lyrics?`<div class="lyrics glass-panel"><h3>Lyrics</h3>${syncedLyricsHTML(current)}</div>`:''}</div>`;$('#bigPlay').onclick=toggle;$('#prev').onclick=prev;$('#next').onclick=next;$('#shuf').onclick=()=>{settings.shuffle=!settings.shuffle;saveSettings();nowPlaying()};$('#rep').onclick=()=>{settings.repeat=settings.repeat==='off'?'all':settings.repeat==='all'?'one':'off';saveSettings();nowPlaying()};$('#seek').oninput=e=>{audio.currentTime=+e.target.value;updateSyncedLyrics()};$('#fav').onclick=async()=>{current.favorite=!current.favorite;await saveMeta(current);nowPlaying()};$('#edit').onclick=()=>editTrack(current);$('#lyricsBtn').onclick=()=>lyricsEditor(current);$('#infoBtn').onclick=()=>musicInfoSearch(current);updateSyncedLyrics()}
function trackMenu(id){let t=tracks.find(x=>x.id===id);sheet.classList.remove('hidden');sheetBody.innerHTML=`<h2>${esc(t.title)}</h2><div class="toolbar"><button class="pill" id="mplay">▶ Play</button><button class="pill" id="mfav">${t.favorite?'♥ Unlike':'♡ Like'}</button><button class="pill" id="medit">✎ Edit Song</button><button class="pill" id="mlyrics">Lyrics / LRC</button><button class="pill" id="minfo">Music Info</button></div>${playlists.length?`<h3>Add to playlist</h3>${playlists.map(p=>`<button class="pill addpl" data-id="${p.id}">${esc(p.name)}</button>`).join('')}`:''}<p><button class="danger" id="delete">Delete from Library</button></p>`;$('#mplay').onclick=()=>play(id);$('#mfav').onclick=async()=>{t.favorite=!t.favorite;await saveMeta(t);render();trackMenu(id)};$('#medit').onclick=()=>editTrack(t);$('#mlyrics').onclick=()=>lyricsEditor(t);$('#minfo').onclick=()=>musicInfoSearch(t);$$('.addpl').forEach(b=>b.onclick=async()=>{let p=playlists.find(x=>x.id===b.dataset.id);if(!p.ids.includes(id))p.ids.push(id);await put('playlists',p);alert('Added to '+p.name)});$('#delete').onclick=async()=>{if(confirm('Delete this song from Melo?')){await del('tracks',id);await del('trackmeta',id);tracks=tracks.filter(x=>x.id!==id);playlists.forEach(async p=>{p.ids=p.ids.filter(x=>x!==id);await put('playlists',p)});if(current?.id===id){audio.pause();current=null}closeSheet();render()}}}
function editTrack(t){sheet.classList.remove('hidden');sheetBody.innerHTML=`<h2>Edit Song</h2><div class="form">${art(t,'big')}<button class="pill" id="chooseArt">Choose Cover Image</button><button class="pill" id="searchArt">Search Cover Online</button><button class="pill" id="searchInfo">Search Music Info</button><label>Title<input id="et" value="${esc(t.title)}"></label><label>Artist<input id="ea" value="${esc(t.artist)}"></label><label>Album<input id="eal" value="${esc(t.album||'')}"></label><label>Genre<input id="eg" value="${esc(t.genre||'')}"></label><label>Year<input id="ey" value="${esc(t.year||'')}"></label><button class="primary" id="saveEdit">Save Changes</button></div>`;$('#chooseArt').onclick=()=>{$('#artInput').dataset.track=t.id;$('#artInput').click()};$('#searchArt').onclick=()=>coverSearch(t);$('#searchInfo').onclick=()=>musicInfoSearch(t);$('#saveEdit').onclick=async()=>{Object.assign(t,{title:$('#et').value.trim()||t.title,artist:$('#ea').value.trim()||'Unknown Artist',album:$('#eal').value.trim(),genre:$('#eg').value.trim(),year:$('#ey').value.trim()});await saveMeta(t);if(current?.id===t.id)current=t;closeSheet();render()}}
function lyricsEditor(t){sheet.classList.remove('hidden');sheetBody.innerHTML=`<h2>Lyrics & LRC</h2><div class="form"><div class="toolbar"><button class="primary" id="findLyrics">Search Synced Lyrics</button><button class="pill" id="importLRC">Import .lrc</button></div><label>Plain lyrics<textarea id="lyricText" placeholder="Plain lyrics">${esc(t.lyrics||'')}</textarea></label><label>Synced LRC<textarea id="lrcText" placeholder="[00:12.50] First line...">${esc(t.syncedLyrics||'')}</textarea></label><button class="primary" id="saveLyrics">Save Lyrics</button></div><div id="lyricStatus" class="sub"></div>`;$('#importLRC').onclick=()=>{$('#lrcInput').dataset.track=t.id;$('#lrcInput').click()};$('#saveLyrics').onclick=async()=>{t.lyrics=$('#lyricText').value;t.syncedLyrics=$('#lrcText').value;lrcCache={source:null,lines:[]};await saveMeta(t);if(current?.id===t.id)current=t;$('#lyricStatus').textContent='Lyrics saved offline.'};$('#findLyrics').onclick=async()=>{let st=$('#lyricStatus');st.textContent='Searching…';try{let u=`https://lrclib.net/api/search?track_name=${encodeURIComponent(t.title)}&artist_name=${encodeURIComponent(t.artist)}`,r=await fetch(u),j=await r.json();let hit=j[0];if(hit){$('#lyricText').value=hit.plainLyrics||'';$('#lrcText').value=hit.syncedLyrics||'';st.textContent=hit.syncedLyrics?'Synced lyrics found. Save to use auto-scrolling lyrics.':'Plain lyrics found; no synced timing was available.'}else st.textContent='No match found. Import an .lrc file or paste lyrics manually.'}catch(e){st.textContent='Search unavailable. You can still import an .lrc file.'}}}
async function musicInfoSearch(t){sheet.classList.remove('hidden');sheetBody.innerHTML=`<h2>Search Music Info</h2><div class="form"><input id="infoQ" value="${esc(t.artist+' '+t.title)}"><button class="primary" id="doInfo">Search Online</button></div><div id="infoResults"></div>`;$('#doInfo').onclick=async()=>{let box=$('#infoResults');box.innerHTML='<p class="sub">Searching…</p>';try{let r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent($('#infoQ').value)}&entity=song&limit=15`),j=await r.json();box.innerHTML=j.results.map((x,i)=>`<button class="info-result" data-i="${i}"><img src="${esc((x.artworkUrl100||'').replace('100x100','300x300'))}"><span><b>${esc(x.trackName||'')}</b><small>${esc(x.artistName||'')} • ${esc(x.collectionName||'')} ${x.releaseDate?'• '+esc(x.releaseDate.slice(0,4)):''}</small></span></button>`).join('')||'<p>No matches found.</p>';$$('.info-result').forEach(b=>b.onclick=async()=>{let x=j.results[+b.dataset.i];if(!confirm(`Use info for ${x.trackName} by ${x.artistName}?`))return;t.title=x.trackName||t.title;t.artist=x.artistName||t.artist;t.album=x.collectionName||t.album;t.genre=x.primaryGenreName||t.genre;t.year=(x.releaseDate||'').slice(0,4)||t.year;let u=(x.artworkUrl100||'').replace('100x100','600x600');if(u)try{t.art=await blobToData(await (await fetch(u)).blob())}catch{}await saveMeta(t);if(current?.id===t.id)current=t;editTrack(t)})}catch(e){box.innerHTML='<p class="sub">Online music info search is unavailable right now.</p>'}};$('#doInfo').click()}
async function coverSearch(t){sheetBody.innerHTML=`<h2>Search Album Cover</h2><div class="form"><input id="coverQ" value="${esc(t.artist+' '+t.title)}"><button class="primary" id="doCover">Search</button></div><div id="covers" class="cover-results"></div>`;$('#doCover').onclick=async()=>{let box=$('#covers');box.innerHTML='Searching…';try{let r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent($('#coverQ').value)}&entity=song&limit=12`),j=await r.json();box.innerHTML=j.results.map((x,i)=>`<img data-url="${esc((x.artworkUrl100||'').replace('100x100','600x600'))}" src="${esc((x.artworkUrl100||'').replace('100x100','300x300'))}">`).join('')||'No covers found';$$('#covers img').forEach(im=>im.onclick=async()=>{try{let b=await (await fetch(im.dataset.url)).blob();t.art=await blobToData(b);await saveMeta(t);if(current?.id===t.id)current=t;editTrack(t)}catch{alert('Could not save this image. Try choosing a cover from Photos instead.')}})}catch{box.innerHTML='Cover search unavailable. You can choose an image from Photos.'}};$('#doCover').click()}
function showList(title,list,p=null){sheet.classList.remove('hidden');sheetBody.innerHTML=`<h2>${esc(title)}</h2>${list.map(row).join('')||empty()}${p?`<p><button class="danger" id="delPl">Delete Playlist</button></p>`:''}`;bindCommon();if(p)$('#delPl').onclick=async()=>{await del('playlists',p.id);playlists=playlists.filter(x=>x.id!==p.id);closeSheet();render()}}
function newPlaylist(){let n=prompt('Playlist name');if(!n?.trim())return;let p={id:uid(),name:n.trim(),ids:[]};playlists.push(p);put('playlists',p);render()}
async function saveSettings(){await put('settings',{id:'main',...settings})}let sleepHandle;function setSleep(m){clearTimeout(sleepHandle);if(m)sleepHandle=setTimeout(()=>audio.pause(),m*60000);alert(m?`Sleep timer set for ${m} minutes.`:'Sleep timer turned off.')}
function closeSheet(){sheet.classList.add('hidden');sheetBody.innerHTML=''}$('#closeSheet').onclick=closeSheet;sheet.onclick=e=>{if(e.target===sheet)closeSheet()};$$('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('#settingsBtn').onclick=()=>{tab='settings';render()};
$('#fileInput').onchange=async e=>{for(let f of e.target.files){let t={id:uid(),title:f.name.replace(/\.[^.]+$/,''),artist:'Unknown Artist',album:'',genre:'',year:'',favorite:false,plays:0,added:Date.now(),position:0,lyrics:'',syncedLyrics:'',art:null,blob:f};tracks.unshift(t);await put('tracks',t);await saveMeta(t)}e.target.value='';render()};$('#lrcInput').onchange=async e=>{let t=tracks.find(x=>x.id==e.target.dataset.track),f=e.target.files[0];if(t&&f){let txt=await f.text();if(!parseLRC(txt).length){alert('This file does not contain valid LRC timestamps.')}else{t.syncedLyrics=txt;lrcCache={source:null,lines:[]};await saveMeta(t);if(current?.id===t.id)current=t;lyricsEditor(t)}}e.target.value=''};$('#artInput').onchange=async e=>{let t=tracks.find(x=>x.id==e.target.dataset.track),f=e.target.files[0];if(t&&f){t.art=await blobToData(f);await saveMeta(t);if(current?.id===t.id)current=t;editTrack(t)}e.target.value=''};function blobToData(b){return new Promise(res=>{let r=new FileReader;r.onload=()=>res(r.result);r.readAsDataURL(b)})}
audio.ontimeupdate=()=>{if(current&&settings.remember&&Date.now()-lastPositionSave>5000){current.position=audio.currentTime;lastPositionSave=Date.now();saveMeta(current).catch(()=>{})}let s=$('#seek');if(s){s.max=audio.duration||1;s.value=audio.currentTime;let ct=$('#ct'),dur=$('#dur');if(ct)ct.textContent=fmt(audio.currentTime);if(dur)dur.textContent=fmt(audio.duration)}updateSyncedLyrics()};audio.onplay=()=>{audio.muted=false;renderMini()};audio.onpause=renderMini;audio.onerror=()=>{console.error('Audio error',audio.error);};audio.onended=()=>{if(settings.repeat==='one'){audio.currentTime=0;audio.play()}else next()};
function mediaSession(){if(!('mediaSession'in navigator)||!current)return;navigator.mediaSession.metadata=new MediaMetadata({title:current.title,artist:current.artist,album:current.album,artwork:current.art?[{src:current.art,sizes:'512x512'}]:[]});[['play',()=>audio.play()],['pause',()=>audio.pause()],['previoustrack',prev],['nexttrack',next],['seekto',d=>audio.currentTime=d.seekTime]].forEach(([a,f])=>{try{navigator.mediaSession.setActionHandler(a,f)}catch{}})}
init();
